stages:
  - build
  - lint
  - test

build-job:
  image: "golang:1.19"
  stage: build
  tags:
    - build
  script:
    - echo "Run Go build for project:"
    - make build

lint-job:
  image: "golangci/golangci-lint:latest"
  stage: lint
  tags:
    - build
  script:
    - echo "Run Golang CI lint for project:"
    - make lint

test-job:
  image: "golangci/golangci-lint:latest"
  stage: test
  tags:
    - build
  script:
    - echo "Run Go test for project:"
    - make test
