stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Run Go build for project:"
    - make build

lint-job:
  stage: test
  script:
    - echo "Run golangci-lint for project:"
    - make lint

check-job:
  stage: test
  script:
    - echo "Run Go test for project:"
    - make test
