// Code generated by ent, DO NOT EDIT.

package ent

import (
	"auth/ent/code"
	"auth/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodeUpdate is the builder for updating Code entities.
type CodeUpdate struct {
	config
	hooks    []Hook
	mutation *CodeMutation
}

// Where appends a list predicates to the CodeUpdate builder.
func (cu *CodeUpdate) Where(ps ...predicate.Code) *CodeUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUserID sets the "user_id" field.
func (cu *CodeUpdate) SetUserID(i int) *CodeUpdate {
	cu.mutation.ResetUserID()
	cu.mutation.SetUserID(i)
	return cu
}

// AddUserID adds i to the "user_id" field.
func (cu *CodeUpdate) AddUserID(i int) *CodeUpdate {
	cu.mutation.AddUserID(i)
	return cu
}

// SetContent sets the "content" field.
func (cu *CodeUpdate) SetContent(s string) *CodeUpdate {
	cu.mutation.SetContent(s)
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CodeUpdate) SetUpdatedAt(t time.Time) *CodeUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetExpiredAt sets the "expired_at" field.
func (cu *CodeUpdate) SetExpiredAt(t time.Time) *CodeUpdate {
	cu.mutation.SetExpiredAt(t)
	return cu
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (cu *CodeUpdate) SetNillableExpiredAt(t *time.Time) *CodeUpdate {
	if t != nil {
		cu.SetExpiredAt(*t)
	}
	return cu
}

// SetRetries sets the "retries" field.
func (cu *CodeUpdate) SetRetries(i int) *CodeUpdate {
	cu.mutation.ResetRetries()
	cu.mutation.SetRetries(i)
	return cu
}

// SetNillableRetries sets the "retries" field if the given value is not nil.
func (cu *CodeUpdate) SetNillableRetries(i *int) *CodeUpdate {
	if i != nil {
		cu.SetRetries(*i)
	}
	return cu
}

// AddRetries adds i to the "retries" field.
func (cu *CodeUpdate) AddRetries(i int) *CodeUpdate {
	cu.mutation.AddRetries(i)
	return cu
}

// Mutation returns the CodeMutation object of the builder.
func (cu *CodeUpdate) Mutation() *CodeMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CodeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	cu.defaults()
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CodeUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CodeUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CodeUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CodeUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := code.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

func (cu *CodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   code.Table,
			Columns: code.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: code.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: code.FieldUserID,
		})
	}
	if value, ok := cu.mutation.AddedUserID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: code.FieldUserID,
		})
	}
	if value, ok := cu.mutation.Content(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: code.FieldContent,
		})
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: code.FieldUpdatedAt,
		})
	}
	if value, ok := cu.mutation.ExpiredAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: code.FieldExpiredAt,
		})
	}
	if value, ok := cu.mutation.Retries(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: code.FieldRetries,
		})
	}
	if value, ok := cu.mutation.AddedRetries(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: code.FieldRetries,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{code.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// CodeUpdateOne is the builder for updating a single Code entity.
type CodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodeMutation
}

// SetUserID sets the "user_id" field.
func (cuo *CodeUpdateOne) SetUserID(i int) *CodeUpdateOne {
	cuo.mutation.ResetUserID()
	cuo.mutation.SetUserID(i)
	return cuo
}

// AddUserID adds i to the "user_id" field.
func (cuo *CodeUpdateOne) AddUserID(i int) *CodeUpdateOne {
	cuo.mutation.AddUserID(i)
	return cuo
}

// SetContent sets the "content" field.
func (cuo *CodeUpdateOne) SetContent(s string) *CodeUpdateOne {
	cuo.mutation.SetContent(s)
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CodeUpdateOne) SetUpdatedAt(t time.Time) *CodeUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetExpiredAt sets the "expired_at" field.
func (cuo *CodeUpdateOne) SetExpiredAt(t time.Time) *CodeUpdateOne {
	cuo.mutation.SetExpiredAt(t)
	return cuo
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (cuo *CodeUpdateOne) SetNillableExpiredAt(t *time.Time) *CodeUpdateOne {
	if t != nil {
		cuo.SetExpiredAt(*t)
	}
	return cuo
}

// SetRetries sets the "retries" field.
func (cuo *CodeUpdateOne) SetRetries(i int) *CodeUpdateOne {
	cuo.mutation.ResetRetries()
	cuo.mutation.SetRetries(i)
	return cuo
}

// SetNillableRetries sets the "retries" field if the given value is not nil.
func (cuo *CodeUpdateOne) SetNillableRetries(i *int) *CodeUpdateOne {
	if i != nil {
		cuo.SetRetries(*i)
	}
	return cuo
}

// AddRetries adds i to the "retries" field.
func (cuo *CodeUpdateOne) AddRetries(i int) *CodeUpdateOne {
	cuo.mutation.AddRetries(i)
	return cuo
}

// Mutation returns the CodeMutation object of the builder.
func (cuo *CodeUpdateOne) Mutation() *CodeMutation {
	return cuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CodeUpdateOne) Select(field string, fields ...string) *CodeUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Code entity.
func (cuo *CodeUpdateOne) Save(ctx context.Context) (*Code, error) {
	var (
		err  error
		node *Code
	)
	cuo.defaults()
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Code)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CodeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CodeUpdateOne) SaveX(ctx context.Context) *Code {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CodeUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CodeUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CodeUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := code.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

func (cuo *CodeUpdateOne) sqlSave(ctx context.Context) (_node *Code, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   code.Table,
			Columns: code.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: code.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Code.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, code.FieldID)
		for _, f := range fields {
			if !code.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != code.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: code.FieldUserID,
		})
	}
	if value, ok := cuo.mutation.AddedUserID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: code.FieldUserID,
		})
	}
	if value, ok := cuo.mutation.Content(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: code.FieldContent,
		})
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: code.FieldUpdatedAt,
		})
	}
	if value, ok := cuo.mutation.ExpiredAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: code.FieldExpiredAt,
		})
	}
	if value, ok := cuo.mutation.Retries(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: code.FieldRetries,
		})
	}
	if value, ok := cuo.mutation.AddedRetries(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: code.FieldRetries,
		})
	}
	_node = &Code{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{code.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
